/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPacakage;

import static com.oracle.jrockit.jfr.ContentType.Bytes;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *Nimbus
 * @author Ran
 */
public class Student_Search extends javax.swing.JFrame {
      ImageIcon format = null;
      byte[] studentphoto=null;   
      int xmouse;
          int ymouse;
      
      
    /**
     * Creates new form Student_Search
     */
    public Student_Search() {
        this.studentphoto = null;
        initComponents();
                        jLabel1.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        jLabel4.setVisible(false);
                        jLabel5.setVisible(false);
                        jLabel6.setVisible(false);
                        jLabel7.setVisible(false);
                        jLabel8.setVisible(false);
                        jLabel9.setVisible(false);
                        jLabel10.setVisible(false);
                        jLabel11.setVisible(false);
                        jLabel12.setVisible(false);
                        jLabel13.setVisible(false);
                        jLabel14.setVisible(false);
                        jLabel15.setVisible(false);
                        jLabel16.setVisible(false);
                        jScrollPane1.setVisible(false);
             
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        student = new javax.swing.JTextField();
        Roll = new javax.swing.JTextField();
        classs = new javax.swing.JTextField();
        section = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        house = new javax.swing.JTextField();
        blood = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        mother = new javax.swing.JTextField();
        father = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        mode = new javax.swing.JTextField();
        admissionno = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jclosebutton = new javax.swing.JButton();
        admissiondate = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        moving = new javax.swing.JLabel();
        imageback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By", "Admission Number", "Name", "Roll-No" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 72, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("House");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 317, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Section");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Roll-No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Class");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Student Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Father's Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Date Of Birth");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 418, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Blood Group");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mother's Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Mode Of Transportation");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Gender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 130, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Date Of Admission");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Residential Address");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Contact Number");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Admission Number");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, -1));

        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 190, 240));

        jScrollPane1.setOpaque(false);

        address.setEditable(false);
        address.setColumns(20);
        address.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        address.setForeground(new java.awt.Color(0, 102, 102));
        address.setLineWrap(true);
        address.setRows(5);
        address.setBorder(null);
        address.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        address.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 660, 230, 110));

        student.setEditable(false);
        student.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        student.setForeground(new java.awt.Color(0, 102, 102));
        student.setBorder(null);
        student.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        student.setOpaque(false);
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        getContentPane().add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 130, 200, 30));

        Roll.setEditable(false);
        Roll.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Roll.setForeground(new java.awt.Color(0, 102, 102));
        Roll.setBorder(null);
        Roll.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Roll.setOpaque(false);
        getContentPane().add(Roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 180, 200, 30));

        classs.setEditable(false);
        classs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        classs.setForeground(new java.awt.Color(0, 102, 102));
        classs.setBorder(null);
        classs.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        classs.setOpaque(false);
        getContentPane().add(classs, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 220, 200, 30));

        section.setEditable(false);
        section.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        section.setForeground(new java.awt.Color(0, 102, 102));
        section.setBorder(null);
        section.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        section.setOpaque(false);
        getContentPane().add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 270, 200, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 270, 50));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 50, 50));

        house.setEditable(false);
        house.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        house.setForeground(new java.awt.Color(0, 102, 102));
        house.setBorder(null);
        house.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        house.setOpaque(false);
        getContentPane().add(house, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 310, 200, 30));

        blood.setEditable(false);
        blood.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        blood.setForeground(new java.awt.Color(0, 102, 102));
        blood.setBorder(null);
        blood.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        blood.setOpaque(false);
        getContentPane().add(blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 360, 200, 30));

        dob.setEditable(false);
        dob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 102, 102));
        dob.setBorder(null);
        dob.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dob.setOpaque(false);
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 410, 200, 30));

        mother.setEditable(false);
        mother.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        mother.setForeground(new java.awt.Color(0, 102, 102));
        mother.setBorder(null);
        mother.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        mother.setOpaque(false);
        getContentPane().add(mother, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 460, 200, 30));

        father.setEditable(false);
        father.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        father.setForeground(new java.awt.Color(0, 102, 102));
        father.setBorder(null);
        father.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        father.setOpaque(false);
        getContentPane().add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 510, 200, 30));

        contact.setEditable(false);
        contact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        contact.setForeground(new java.awt.Color(0, 102, 102));
        contact.setBorder(null);
        contact.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        contact.setOpaque(false);
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 560, 200, 30));

        mode.setEditable(false);
        mode.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        mode.setForeground(new java.awt.Color(0, 102, 102));
        mode.setBorder(null);
        mode.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        mode.setOpaque(false);
        getContentPane().add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 610, 200, 30));

        admissionno.setEditable(false);
        admissionno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        admissionno.setForeground(new java.awt.Color(0, 102, 102));
        admissionno.setBorder(null);
        admissionno.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        admissionno.setOpaque(false);
        getContentPane().add(admissionno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 110, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("-");
        jButton4.setToolTipText("minimize");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 10, -1, 30));

        jclosebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jclosebutton.setForeground(new java.awt.Color(204, 204, 204));
        jclosebutton.setText("X");
        jclosebutton.setToolTipText("close");
        jclosebutton.setBorderPainted(false);
        jclosebutton.setContentAreaFilled(false);
        jclosebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jclosebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jclosebuttonMouseMoved(evt);
            }
        });
        jclosebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclosebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jclosebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 10, -1, 30));

        admissiondate.setEditable(false);
        admissiondate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        admissiondate.setForeground(new java.awt.Color(0, 102, 102));
        admissiondate.setBorder(null);
        admissiondate.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        admissiondate.setOpaque(false);
        getContentPane().add(admissiondate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 110, 30));

        gender.setEditable(false);
        gender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 102, 102));
        gender.setBorder(null);
        gender.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        gender.setOpaque(false);
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 110, 30));

        moving.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movingMouseDragged(evt);
            }
        });
        moving.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movingMousePressed(evt);
            }
        });
        getContentPane().add(moving, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        imageback.setForeground(new java.awt.Color(0, 102, 102));
        imageback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentsearch.png"))); // NOI18N
        imageback.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imagebackMouseMoved(evt);
            }
        });
        getContentPane().add(imageback, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 770, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Search = jTextField1.getText();
            
        if(jComboBox1.getSelectedIndex()==0 && Search.isEmpty() )
            JOptionPane.showMessageDialog(this,"Please  Select and Fill the detail");
          
       else   if (jComboBox1.getSelectedIndex()==0)
             JOptionPane.showMessageDialog(this,"Please  Select Search Option");
        
       else if (Search.isEmpty())
           JOptionPane.showMessageDialog(this,"Please Fill the Detail");
        
       else{
       
           if(jComboBox1.getSelectedIndex()==1)
                    
           
               try
                        {
                        
                        Class.forName("java.sql.DriverManager");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SIM","root","student");
                        Statement stmt = (Statement) con.createStatement();
                        String query= "Select Admission ,Studentname,Rollno,Fathername,Mothername,Contactnumber,Mode,Address,Class,Sec,House,Blood,Gender,Studentphoto,birthday,admissiondate FROM school"
                                + " Where Admission='"+Search+ "';";
                        
                        ResultSet rs= stmt.executeQuery(query);
                        if(rs.next())
                        {
                        
                        String admissionnumber   = rs.getString("Admission");
                        String Studentname   =  rs.getString("Studentname");
                        String Rollno        =  rs.getString("Rollno");
                        String Fathername    =  rs.getString("Fathername");
                        String Mothername    =  rs.getString("Mothername");
                        String Contactnumber =  rs.getString("Contactnumber");
                        String Mode          =  rs.getString("Mode");
                        String Address       =  rs.getString("Address");
                        String Class         =  rs.getString("Class");
                        String Sec           =  rs.getString("Sec");
                        String House         =  rs.getString("House");
                        String Blood         =  rs.getString("Blood");
                        String Gender        =  rs.getString("Gender");    
                        String birthday      =  rs.getString("birthday");
                        String Admissiondate =  rs.getString("admissiondate");
                         studentphoto =rs.getBytes("Studentphoto");
                        format = new ImageIcon(studentphoto);
                        
                        
                        
                        jLabel1.setVisible(true);
                        jLabel2.setVisible(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
                        jLabel7.setVisible(true);
                        jLabel8.setVisible(true);
                        jLabel9.setVisible(true);
                        jLabel10.setVisible(true);
                        jLabel11.setVisible(true);
                        jLabel12.setVisible(true);
                        jLabel13.setVisible(true);
                        jLabel14.setVisible(true);
                        jLabel15.setVisible(true);
                        jLabel16.setVisible(true);
                        jScrollPane1.setVisible(true);
        
                          
               
                        jLabel16.setIcon(format);
                        Roll.setText(Rollno);
                        admissiondate.setText(Admissiondate);
                        blood.setText(Blood);
                        classs.setText(Class);
                        dob.setText(birthday);
                        father.setText(Fathername);
                        gender.setText(Gender);
                        house.setText(House);
                        mode.setText(Mode);
                        mother.setText(Mothername);
                        address.setText(Address);
                        section.setText(Sec);
                        student.setText(Studentname);
                        contact.setText(Contactnumber);
                        admissionno.setText(admissionnumber);
                    
                        
                        }
                                               
                        else
                            JOptionPane.showMessageDialog(this, "Sorry!No Such Admission Number");
                      
                        }
         
           catch(Exception e)
           {
           JOptionPane.showMessageDialog(this, e.getMessage());
           }
               
           else if (jComboBox1.getSelectedIndex()==2)
                
               try
                        {
                        
                        Class.forName("java.sql.DriverManager");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SIM","root","student");
                        Statement stmt = (Statement) con.createStatement();
                        String query= "Select Admission ,Studentname,Rollno,Fathername,Mothername,Contactnumber,Mode,Address,Class,Sec,House,Blood,Gender,Studentphoto,birthday,admissiondate FROM school"
                                + " Where Studentname='"+Search+ "';";
                        
                        ResultSet rs= stmt.executeQuery(query);
                        int Found=0;
                        while(rs.next())
                        {
                        
                        String admissionnumber   = rs.getString("Admission");
                        String Studentname   =  rs.getString("Studentname");
                        String Rollno        =  rs.getString("Rollno");
                        String Fathername    =  rs.getString("Fathername");
                        String Mothername    =  rs.getString("Mothername");
                        String Contactnumber =  rs.getString("Contactnumber");
                        String Mode          =  rs.getString("Mode");
                        String Address       =  rs.getString("Address");
                        String Class         =  rs.getString("Class");
                        String Sec           =  rs.getString("Sec");
                        String House         =  rs.getString("House");
                        String Blood         =  rs.getString("Blood");
                        String Gender        =  rs.getString("Gender");    
                        String birthday      =  rs.getString("birthday");
                        String Admissiondate =  rs.getString("admissiondate");
  
                         studentphoto =rs.getBytes("Studentphoto");
                        format = new ImageIcon(studentphoto);
                          
                        
                        
                        
                        jLabel1.setVisible(true);
                        jLabel2.setVisible(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
                        jLabel7.setVisible(true);
                        jLabel8.setVisible(true);
                        jLabel9.setVisible(true);
                        jLabel10.setVisible(true);
                        jLabel11.setVisible(true);
                        jLabel12.setVisible(true);
                        jLabel13.setVisible(true);
                        jLabel14.setVisible(true);
                        jLabel15.setVisible(true);
                        jLabel16.setVisible(true);
                        jScrollPane1.setVisible(true);
                  
               
                        jLabel16.setIcon(format);
                        Roll.setText(Rollno);
                        admissiondate.setText(Admissiondate);
                        blood.setText(Blood);
                        classs.setText(Class);
                        dob.setText(birthday);
                        father.setText(Fathername);
                        gender.setText(Gender);
                        house.setText(House);
                        mode.setText(Mode);
                        mother.setText(Mothername);
                        address.setText(Address);
                        section.setText(Sec);
                        student.setText(Studentname);
                        contact.setText(Contactnumber);
                        admissionno.setText(admissionnumber);
                    
                        
                        Found++;
                        //Increment the variable to indicaye a matching
                        //record has been font
                        
                        
                        
                        
                        
                        }
                                               
                        if (Found==0)
                            JOptionPane.showMessageDialog(this,"Sorry! NO Such Student");
                      
                        }
         
           catch(Exception e)
           {
           JOptionPane.showMessageDialog(this, e.getMessage());
           }
               
               
        else 
                
        try
                        {
                        
                        Class.forName("java.sql.DriverManager");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SIM","root","student");
                        Statement stmt = (Statement) con.createStatement();
                        String query= "Select Admission ,Studentname,Rollno,Fathername,Mothername,Contactnumber,Mode,Address,Class,Sec,House,Blood,Gender,Studentphoto,birthday,admissiondate FROM school"
                                + " Where Rollno='"+Search+ "';";
                        
                        ResultSet rs= stmt.executeQuery(query);
                        if(rs.next())
                        {
                        
                        String admissionnumber   = rs.getString("Admission");
                        String Studentname   =  rs.getString("Studentname");
                        String Rollno        =  rs.getString("Rollno");
                        String Fathername    =  rs.getString("Fathername");
                        String Mothername    =  rs.getString("Mothername");
                        String Contactnumber =  rs.getString("Contactnumber");
                        String Mode          =  rs.getString("Mode");
                        String Address       =  rs.getString("Address");
                        String Class         =  rs.getString("Class");
                        String Sec           =  rs.getString("Sec");
                        String House         =  rs.getString("House");
                        String Blood         =  rs.getString("Blood");
                        String Gender        =  rs.getString("Gender");    
                        String birthday      =  rs.getString("birthday");
                        String Admissiondate =  rs.getString("admissiondate");
                        studentphoto =rs.getBytes("Studentphoto");
                        format = new ImageIcon(studentphoto);
                          
                        
                        
                        
                        jLabel1.setVisible(true);
                        jLabel2.setVisible(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
                        jLabel7.setVisible(true);
                        jLabel8.setVisible(true);
                        jLabel9.setVisible(true);
                        jLabel10.setVisible(true);
                        jLabel11.setVisible(true);
                        jLabel12.setVisible(true);
                        jLabel13.setVisible(true);
                        jLabel14.setVisible(true);
                        jLabel15.setVisible(true);
                        jLabel16.setVisible(true);
                        jScrollPane1.setVisible(true);
            
               
                        jLabel16.setIcon(format);
                        Roll.setText(Rollno);
                        admissiondate.setText(Admissiondate);
                        blood.setText(Blood);
                        classs.setText(Class);
                        dob.setText(birthday);
                        father.setText(Fathername);
                        gender.setText(Gender);
                        house.setText(House);
                        mode.setText(Mode);
                        mother.setText(Mothername);
                        address.setText(Address);
                        section.setText(Sec);
                        student.setText(Studentname);
                        contact.setText(Contactnumber);
                        admissionno.setText(admissionnumber);
                    
                        
                        }
                                               
                        else
                            JOptionPane.showMessageDialog(this, "Sorry!No Such Roll Number");
                      
                        }
         
           catch(Exception e)
           {
           JOptionPane.showMessageDialog(this, e.getMessage());
           }
       
       
     
       
       
               
       
       
       
       
       
        
        
               }    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttoon/searchmove.png")));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttoon/searchpresse.png")));
    }//GEN-LAST:event_jButton1MousePressed

    private void imagebackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagebackMouseMoved
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
    }//GEN-LAST:event_imagebackMouseMoved

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttoon/searchmove.png")));
    }//GEN-LAST:event_jButton1MouseReleased

    private void movingMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse , y-ymouse);
    }//GEN-LAST:event_movingMouseDragged

    private void movingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingMousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_movingMousePressed

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setState(Student_Search.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jclosebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jclosebuttonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jclosebuttonMouseMoved

    private void jclosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclosebuttonActionPerformed
        // TODO add your handling code here:
        new StudentHOme().setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_jclosebuttonActionPerformed

    /**
     * @param args the command lie arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Roll;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField admissiondate;
    private javax.swing.JTextField admissionno;
    private javax.swing.JTextField blood;
    private javax.swing.JTextField classs;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField father;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField house;
    private javax.swing.JLabel imageback;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jclosebutton;
    private javax.swing.JTextField mode;
    private javax.swing.JTextField mother;
    private javax.swing.JLabel moving;
    private javax.swing.JTextField section;
    private javax.swing.JTextField student;
    // End of variables declaration//GEN-END:variables

    private void printAll(Graphics grphcs, MessageFormat header) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void printAll(Graphics grphcs, MessageFormat header, MessageFormat footer) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
